services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 5s
      timeout: 30s
      retries: 5
  go:
    image: golang:1.21
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    command: "go run main.go"



